import type { Metadata } from 'next'
import './globals.css'
import ThemeRegistry from './components/ThemeRegistry'
import SidebarMenu from "@/app/components/SidebarMenu/SidebarMenu";
import Navbar from "@/app/components/Navbar/Navbar";
import {width} from "@mui/system";

export const metadata: Metadata = {
  title: 'Next App MUI',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
        <ThemeRegistry>
            <body>
                <div className={'container'}>
                    <SidebarMenu/>
                    <div style={{width: '100%'}}>
                        <Navbar/>
                        <div style={{padding: '0px 16px'}}>
                            {children}
                        </div>
                    </div>

                </div>
            </body>
        </ThemeRegistry>
      </html>
  )
}